# This is the Snakemake configuration file that specifies paths and 
# and options for the pipeline. Anybody wishing to use
# the provided snakemake pipeline should first fill out this file with paths to
# their own data, as the Snakefile requires it.
# Every config option has reasonable defaults unless it is labeled as "required."
# All paths are relative to the directory that Snakemake is executed in.
# Note: this file is written in the YAML syntax (https://learnxinyminutes.com/docs/yaml/)

# Path to directory in which to store the input data for the pipeline
# The input data will be downloaded to this directory if it does not exist
# Defaults to "data" if not specified
data_dir: ../teams/CSE284_SP21_A00/team2

# Path to the directory in which to store all output of the pipeline
# Defaults to "results" if not specified
out: results

# Which variant callers should we use?
# Defaults to all if this option is set to a false value
callers: false

# Which field in each caller's VCF contains genotype scores?
# This information is useful for creating precision-recall curves
# You can specify null if the caller does not output a scoring field
# If not specified (or falsey), this will default to GQX (or GQ, otherwise)
caller_score:
    picky: null
    sniffles: null
    cutesv: null # GQ exists but it's empty -__-
    longshot: false

# Path to a gzipped VCF containing known, high-confidence variants for NA12878
# An index (.tbi) file with the same filename must exist in the same directory
# required
truth: /datasets/cs284-sp21-A00-public/ps4/HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_PGandRTGphasetransfer.vcf.gz

# Path to the fasta file for the hg38 ref genome
# An index (.fai) file with the same filename must exist in the same directory
# required
ref: ../teams/CSE284_SP21_A00/team2/ref/GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta

# Are we in development mode?
# If this option is set to true, the pipeline will use the input data in "development"
# below instead of downloading a full dataset to the data_dir.
# Defaults to false if not specified
develop: true

# Inputs for development mode
# "illumina" refers to a CRAM file containing short-read, illumina reads
# "ont" refers to a BAM file containing long reads for a single chromosme sequenced
#       using Oxford Nanopore
# "ref" is the fasta file for the hg38 ref genome
# Note: each file must have a corresponding index in the same directory
develop_in:
    tech:
        illumina: ../teams/CSE284_SP21_A00/team2/test_data/illumina/HG001.GRCh38_full_plus_hs38d1_analysis_set_minus_alts.300x.chr22.bam
        ont: ../teams/CSE284_SP21_A00/team2/test_data/ont/NA12878-minion-ul_GRCh38.decoys.chr22.bam
        pacbio: ../teams/CSE284_SP21_A00/team2/test_data/pacbio/HG001_GRCh38.haplotag.RTG.trio.decoys.chr22.bam
            
full_run:
    tech:
        ont: ../teams/CSE284_SP21_A00/team2/data/ont/NA12878-minion-ul_GRCh38.decoys.bam
        illumina: ../teams/CSE284_SP21_A00/team2/data/illumina/RMNISTHS_30xdownsample.bam
        pacbio: ../teams/CSE284_SP21_A00/team2/data/pacbio/HG001_GRCh38.haplotag.RTG.trio.decoys.bam

nanosv_bed: ../teams/CSE284_SP21_A00/team2/ref/hg38_nanosv.bed
wittyer_config: ~/Varbench/config/wittyer_config.json